---
# declare resources
resources:
- name: source-master
  type: git
  icon: github-circle
  source:
    uri: https://github.com/everythingeverywhere/spring-concourse-kpack
    branch: master
- name: source-stable
  type: git
  icon: github-circle
  source:
    uri: git@github.com:everythingeverywhere/spring-concourse-kpack.git
    branch: stable
    private_key: ((github-private-key))
jobs:
- name: run-tests
  plan:
  - get: source-master
    trigger: true
  - task: first-task
    config: 
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven, tag: latest}
      inputs:
      - name: source-master
      run:
          path: sh
          args:
          - -exec
          - |
            echo 'pwd ::'
            pwd 
            echo 'ls ::'
            ls  
            cd source-master
            echo 'pwd ::'
            pwd 
            echo 'ls ::'
            ls  
            mvn package
- name: promote-to-stable
  plan:
  - get: source-master
    trigger: true
    passed: [run-tests]
  - get: source-stable
  - put: source-stable
    params:
      repository: source-master